import type { ComponentCategory } from "@/types";
import { marketSources } from "@/content/builds/researched";

const data: Record<string, { name: string; short: string; intro: string; matters: string[]; tiers: [string, string][]; compatibility: string[]; mistakes: string[] }> = {
  motherboard: { name: "Motherboard", short: "Motherboard", intro: "Choose the board around the CPU socket, memory type, expansion needs and power delivery—not around decorative features alone.", matters: ["CPU socket and BIOS support", "VRM quality matched to the processor", "M.2 slots, USB and networking", "Form factor and case compatibility"], tiers: [["AM4 value", "Used A520/B550 boards remain the lowest-cost route for the ₹40k–₹1L builds."], ["AM5", "B650 is the sensible starting point; X870 is for connectivity, not automatic gaming performance."]], compatibility: ["AM4 CPUs require AM4 boards and DDR4; AM5 CPUs require AM5 boards and DDR5.", "Confirm BIOS support for X3D processors before buying used."], mistakes: ["Buying a board without the needed BIOS", "Paying for Wi-Fi or PCIe features you will not use"] },
  ram: { name: "RAM", short: "RAM", intro: "Capacity, dual-channel operation and platform compatibility matter more than chasing the highest advertised speed.", matters: ["16GB is the budget floor; 32GB is the practical modern target", "Two matched sticks enable dual-channel", "DDR4 and DDR5 are not interchangeable", "Check motherboard QVL and stable timings"], tiers: [["AM4", "Used 16GB or 32GB DDR4-3200/3600 keeps lower tiers viable."], ["AM5", "32GB DDR5-6000 is the normal gaming target; current prices are volatile."]], compatibility: ["Use matched modules where possible.", "Enable EXPO/XMP only after confirming stability."], mistakes: ["Using one stick and losing dual-channel bandwidth", "Choosing capacity while ignoring unusually high local pricing"] },
  ssd: { name: "SSD & Storage", short: "SSD", intro: "A good NVMe SSD improves responsiveness and load times, but it does not replace GPU budget in a gaming build.", matters: ["Capacity before headline sequential speed", "NAND type, endurance and warranty", "Motherboard M.2 slot generation", "Keep free space for sustained performance"], tiers: [["Value", "500GB–1TB NVMe is enough to start, but modern games make 1TB more comfortable."], ["High-end", "2TB is convenient when the GPU budget is already protected."]], compatibility: ["Check M.2 length and whether using a slot disables SATA or PCIe lanes.", "Use the motherboard heatsink when supplied."], mistakes: ["Buying a tiny boot drive for a large game library", "Comparing only advertised sequential speed"] },
  psu: { name: "Power Supply (PSU)", short: "PSU", intro: "A reliable PSU is the safety-critical foundation of a gaming PC; wattage alone does not establish quality.", matters: ["Platform quality and warranty", "Correct GPU connectors", "Realistic system headroom", "ATX generation and efficiency"], tiers: [["Budget", "A reputable 500W–650W Bronze unit is preferable to an unknown higher-wattage model."], ["High-end", "750W–1000W Gold is appropriate when GPU transient demand rises."]], compatibility: ["Check native GPU power connectors and cable routing.", "Never reuse modular cables from another PSU."], mistakes: ["Choosing by wattage sticker alone", "Buying a questionable used PSU"] },
  case: { name: "PC Case", short: "Case", intro: "The case must fit the motherboard, cooler and GPU while moving enough air through the system.", matters: ["Mesh intake and fan support", "GPU length and thickness", "CPU cooler height or radiator size", "Front-panel and dust-filter design"], tiers: [["Value", "A mesh-front mid-tower is usually a better gaming choice than a sealed glass-front case."], ["High-end", "Spend on clearance and quiet airflow before RGB or premium materials."]], compatibility: ["Check motherboard form factor and GPU clearance.", "Confirm radiator placement does not block memory or GPU space."], mistakes: ["Ignoring GPU thickness", "Treating included fans as an airflow guarantee"] },
  "cpu-cooler": { name: "CPU Cooler", short: "CPU cooler", intro: "Cooling should match sustained power, socket support, case clearance and noise expectations.", matters: ["Socket mounting compatibility", "Thermal capacity and fan noise", "Case clearance", "Air cooler simplicity versus AIO complexity"], tiers: [["Value", "Bundled cooling or a basic tower can be enough for efficient six-core CPUs."], ["High-end", "Premium air or a correctly sized AIO suits hotter high-core or X3D systems."]], compatibility: ["Check socket mounting hardware and cooler height.", "Check radiator length, thickness and fan clearance."], mistakes: ["Assuming every stock cooler is sufficient", "Buying an AIO without checking case support"] },
};

export const researchedComponentCategories: ComponentCategory[] = Object.entries(data).map(([slug, item]) => ({
  slug, name: item.name, shortName: item.short, title: `Best ${item.name} for Gaming PCs in India`, metaDescription: `${item.name} buying guidance for researched Indian gaming PC builds.`, intro: item.intro, whatMatters: item.matters,
  budgetTiers: item.tiers.map(([tier, guidance]) => ({ tier, guidance })), compatibilityNotes: item.compatibility, commonMistakes: item.mistakes,
  faqs: [{ question: `What matters most when choosing a ${item.short}?`, answer: item.matters[0] + ". " + item.matters[1] + "." }, { question: "Should I buy this component used?", answer: slug === "psu" || slug === "ssd" ? "Prefer new hardware with a clear warranty because failure or wear is difficult to assess safely." : "Used can make sense when the part is tested, the price is materially lower and bill/warranty evidence is available." }], relatedBuilds: ["40000", "50000", "75000", "100000", "150000"], relatedGuides: [], lastUpdated: "2026-08-30", sources: marketSources,
}));
