import type { Guide } from "@/types";
import { marketSources } from "@/content/builds/researched";

type GuideSeed = { slug: string; title: string; cluster: string; intro: string; sections: [string, string][]; builds?: string[]; components?: { label: string; href: string }[] };

const seeds: GuideSeed[] = [
  { slug: "best-cpu-for-gaming", title: "Best CPU for Gaming in India", cluster: "CPU", intro: "Pick the CPU after setting the GPU and resolution target; the fastest processor is not automatically the best value.", sections: [["Start with the GPU", "At 1080p, CPU limits appear sooner; at 1440p and 4K, the GPU usually dominates. Match CPU spend to the target frame rate."], ["AM4 versus AM5", "AM4 remains the value choice in the used ₹40k–₹1L range. New AM5 is the better starting point above ₹1L when future CPU upgrades matter."], ["Our decision rule", "Prefer a six-core chip for mainstream gaming, eight cores for high-end or streaming, and X3D models only when current pricing justifies the gaming uplift."]], builds: ["50000", "100000", "150000"] },
  { slug: "cpu-buying-guide", title: "CPU Buying Guide for Gaming PCs", cluster: "CPU", intro: "A practical checklist for selecting a gaming CPU without overpaying for cores you will not use.", sections: [["Check socket and memory", "CPU, motherboard socket and RAM generation must be compatible. AM4 uses DDR4; AM5 uses DDR5."], ["Check workload", "Competitive gaming values frame-time consistency and single-thread speed; streaming and creation benefit from more cores."], ["Check the complete platform", "Compare CPU, motherboard, RAM and cooler together instead of comparing processor prices in isolation."]] },
  { slug: "cpu-cores-for-gaming", title: "How Many CPU Cores Do You Need for Gaming?", cluster: "CPU", intro: "Six cores remains a practical gaming baseline, while eight cores gives more headroom for modern games and background workloads.", sections: [["Six cores", "A good baseline for a discrete GPU and ordinary gaming, especially when the GPU is the main limit."], ["Eight cores", "Useful for high-refresh gaming, simulation-heavy games, streaming and multitasking."], ["More than eight", "Only worth prioritising when your games or non-gaming workloads actually use the extra parallelism."]] },
  { slug: "am4-vs-am5", title: "AM4 vs AM5: Which Platform Should You Buy?", cluster: "Platform", intro: "AM4 saves money today; AM5 costs more but preserves a clearer CPU upgrade path.", sections: [["AM4 value", "Used Ryzen and B550 parts can leave more budget for the GPU in builds up to ₹1L."], ["AM5 longevity", "AM5 requires DDR5 and a compatible board, but later CPU upgrades do not require replacing the platform."], ["Decision", "Choose AM4 when GPU value is the priority and AM5 when you want a new system with future CPU headroom."]] },
  { slug: "ddr4-vs-ddr5", title: "DDR4 vs DDR5 for Gaming", cluster: "Memory", intro: "Memory generation is a platform decision, not a simple speed comparison.", sections: [["DDR4", "Lower-cost DDR4 is why used AM4 remains attractive in the lower budget tiers."], ["DDR5", "DDR5 is required by AM5 and provides the platform's current upgrade path, but Indian pricing must be checked before purchase."], ["What matters", "Use two matched modules, sufficient capacity and stable timings before chasing headline frequency."]] },
  { slug: "best-gpu-for-1080p", title: "Best GPUs for 1080p Gaming in India", cluster: "GPU", intro: "1080p rewards value and high minimum frame rates more than flagship hardware.", sections: [["Budget", "Used RX 6600, RTX 2060 and similar cards can make sense when tested and priced with warranty risk in mind."], ["High refresh", "RTX 4060, RX 7600 and newer equivalents are sensible starting points; compare real prices rather than MSRP."], ["VRAM", "8GB is a practical floor for many current 1080p games, but game settings and texture packs still matter."]] },
  { slug: "best-gpu-for-1440p", title: "Best GPUs for 1440p Gaming in India", cluster: "GPU", intro: "1440p shifts more of the budget toward the GPU, with 12GB or more increasingly useful for high settings.", sections: [["Value 1440p", "A used RTX 4070, RX 7800 XT or comparable card can deliver strong value if condition and warranty are verified."], ["High refresh", "New RX 9070-class and RTX 5070-class cards should be compared at the exact Indian prices available today."], ["Ray tracing", "NVIDIA features may justify a premium for some games; AMD can be stronger for rasterisation per rupee."]] },
  { slug: "how-much-vram-do-you-need", title: "How Much VRAM Do You Need for Gaming?", cluster: "GPU", intro: "VRAM capacity matters most when resolution, texture quality and ray tracing increase.", sections: [["1080p", "8GB is a reasonable modern target, though performance still depends on the GPU core."], ["1440p", "12GB is more comfortable, with 16GB useful for demanding textures and longer ownership."], ["4K", "Prioritise both GPU performance and VRAM; capacity alone cannot make a slow GPU fast."]] },
  { slug: "how-to-build-a-gaming-pc", title: "How to Build a Gaming PC", cluster: "Build fundamentals", intro: "A complete sequence from budget to tested system, with compatibility checks before assembly.", sections: [["Plan", "Choose resolution, games, budget and GPU first, then match CPU, board, memory, storage, PSU, case and cooler."], ["Assemble", "Install CPU, cooler, memory and SSD on the board first; mount the board, PSU and GPU in the case and route cables safely."], ["Configure and test", "Update BIOS when needed, install the operating system and drivers, then check temperatures, stability and storage health before gaming."]] },
  { slug: "pc-component-compatibility", title: "PC Component Compatibility Checklist", cluster: "Build fundamentals", intro: "Use this checklist before buying parts so socket, power, physical clearance and storage interfaces all line up.", sections: [["CPU and motherboard", "The socket and supported CPU list must match; used AM4 boards may need a BIOS update."], ["RAM and storage", "AM4 requires DDR4, AM5 requires DDR5. Check M.2 slots, lanes and drive size."], ["GPU, PSU, cooler and case", "Check GPU length, PSU connectors, cooler socket/height and radiator clearance together."]] },
  { slug: "4k-gaming", title: "4K Gaming PC Guide", cluster: "Resolution", intro: "4K is primarily a GPU and display problem; upscaling is now part of the realistic target rather than an afterthought.", sections: [["4K 60", "A strong 16GB-class GPU with upscaling can make 4K viable across a wider set of games."], ["4K high refresh", "High-refresh 4K requires flagship GPU spend and game-specific optimisation; no universal FPS promise is credible."], ["CPU relevance", "The CPU still matters for simulation and minimum frames, but GPU selection dominates the budget."]], builds: ["150000", "200000", "250000"] },
  { slug: "gaming-pc-vs-gaming-laptop", title: "Gaming PC vs Gaming Laptop", cluster: "Buying decision", intro: "Choose a desktop for upgradeability and sustained performance, or a laptop for portability and an all-in-one purchase.", sections: [["Desktop advantages", "A desktop is easier to repair and upgrade, and its larger cooling system generally sustains higher performance."], ["Laptop advantages", "A laptop includes display, battery and portability, but GPU performance, thermals and upgrade options vary by model."], ["Decision", "Buy the desktop when you already have peripherals and value long-term component replacement; choose the laptop when mobility is essential."]] },
  { slug: "how-much-ram-for-gaming", title: "How Much RAM Do You Need for Gaming?", cluster: "Memory", intro: "16GB is the entry point; 32GB is the safer modern recommendation for gaming plus background applications.", sections: [["16GB", "Still workable for focused gaming, especially in lower-cost builds."], ["32GB", "The practical target for modern games, streaming, browsers and multitasking."], ["64GB", "A specialist choice for creation, virtual machines or unusually heavy workloads rather than ordinary gaming."]], builds: ["50000", "100000", "150000"] },
];

export const researchedGuides: Guide[] = seeds.map((seed) => ({ slug: seed.slug, title: seed.title, metaDescription: seed.intro, cluster: seed.cluster, intro: seed.intro, sections: seed.sections.map(([heading, body]) => ({ heading, body })), faqs: [{ question: "How current is this guidance?", answer: "The recommendation is reviewed against current Indian pricing and platform availability; exact prices and stock can change after the checked date." }, { question: "Should I buy used parts?", answer: "Only when the part can be tested and the seller can provide condition, invoice and warranty evidence. Avoid questionable used PSUs." }], relatedBuilds: seed.builds ?? ["50000", "75000", "100000", "150000"], relatedGuides: [], relatedComponents: seed.components ?? [{ label: "CPU hub", href: "/components/cpu" }, { label: "GPU hub", href: "/components/gpu" }], lastUpdated: "2026-08-30", sources: marketSources }));
